services:
  app:
    image: golang:1.26-alpine
    container_name: go_app
    restart: "no"
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    command: sh -c "go mod download && go run ./cmd/api/main.go"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - app-network

  postgres:
    image: postgres:18-alpine
    container_name: go_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  memcached:
    image: memcached:1.6-alpine
    container_name: go_memcached
    command: [ "-m", "64", "-t", "2" ]
    ports:
      - "11211:11211"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'stats' | nc -w 2 localhost 11211 | grep -q 'STAT'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  migration:
    image: migrate/migrate
    restart: on-failure
    command: --path=/migrations/ --database="${DB_CONNECTION}" up
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:
  go-mod-cache:

networks:
  app-network:
    driver: bridge
